insert into role(role_name) value('平衡车间');
insert into role(role_name) value('ECO生产统计组');
insert into role(role_name) value('ECO生产管理组');
insert into role(role_name) value('仓库组');
insert into role(role_name) value('品管外观检验组');
insert into role(role_name) value('品管染判组');
insert into role(role_name) value('是否包装组');
insert into role(role_name) value('加弹管理组');
insert into role(role_name) value('品检主管');
insert into role(role_name) value('标签打印组');
insert into role(role_name) value('加弹生管组');
insert into role(role_name) value('纺丝计划组');
insert into role(role_name) value('admin');
insert into role(role_name) value('生产计划组');
insert into role(role_name) value('包装组');

insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,3,24,-1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,22,1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,22,2);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,22,3);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,22,4);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,22,7);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,22,8);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,21,1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,21,2);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,21,3);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,21,4);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,21,7);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,21,8);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,2);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,3);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,4);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,7);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,8);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,13);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,18,23);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,15,1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,15,2);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,15,3);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,15,4);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,15,7);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,15,8);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,19,1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,19,2);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,19,4);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,17,1);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,17,2);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,17,3);
insert into role_permission(role_id,permission_id,menu_id,operation_id) value(1,2,17,4);

-- insert into role_permission(role_id,permission_id,menu_id,operation_id) value(13,1,1,1);
-- insert into role_permission(role_id,permission_id,menu_id,operation_id) value(13,1,1,2);
-- insert into role_permission(role_id,permission_id,menu_id,operation_id) value(13,1,1,3);
-- insert into role_permission(role_id,permission_id,menu_id,operation_id) value(13,1,1,4);
insert into user_role(user_id,role_id) value(20120485,1);